### ISSUE TITLE
ERROR in command, cant fix it, already tried everything.

### ISSUE THREAD

**Issue by Lu1s-glitch** [Ayantaker/SpyderC2#2]
# Error
-------------------
![ERROR](https://user-images.githubusercontent.com/119898049/219006052-77074740-81c7-47a9-b23f-49868b32eb9a.png)
-------------------
`error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/ kali linux`
-------------------
`ERROR: Failed building wheel for psutil
  Running setup.py clean for psutil
Failed to build psutil
ERROR: Could not build wheels for psutil which use PEP 517 and cannot be installed directly`

**Comment by Ayantaker** [comment]
Hi can you try this workaround. In the requirements.txt add this library - chardet and run the below command to generate the stager. You might have to do a docker-compose down and remove the docker image called `spyderc2_python` for it to take effect Let me know if this works, then I will integrate this fix when I get the time.

`sudo docker run -v "$(pwd):/src/" --entrypoint /bin/bash cdrx/pyinstaller-windows:python3 -c "python -m pip install --upgrade pip  && /entrypoint.sh" && sudo ../../utilities/upx/upx ../tmp/dist/windows/stager.exe`

**Comment by Ayantaker** [comment]
Or if you want you can submit a PR with the fix if it works.

**Comment by Lu1s-glitch** [comment]
It worked, thanks!!

But when i execute the stager.exe in my windows, it doesnt connect back to my C&C, dont known whats happening.

**Comment by Ayantaker** [comment]
Nice!

I would check two things :
1. Try pinging the C&C ip from windows and see if it's reachable. If not you would need to have it bridged netwroking. 
2. Windows defenders real time protection if off

**Comment by Lu1s-glitch** [comment]
It pings, and real time protection is off , it shows me this:
![Failed](https://user-images.githubusercontent.com/119898049/219357134-9bca283b-1774-4cb5-9d14-f9dfc5504ed8.png)

**Comment by Ayantaker** [comment]
You can try this to debug :

In the stager.spec file, set the debug and console flag as True. Generate the stager again and on windows run the exe from cmd. it should show you the error.

**Comment by Ayantaker** [comment]
The issue should be fixed with the latest commit. Let me know if you still face issues.
